#### 코드 3-1 넘파이의 행렬 계산

In [1]:
import numpy as np

a = np.array([2, 1])
print(a)

b = np.array([3, 2, 1])
print(b)

A = np.array([[2, 4, 1], [6, 3, 5]])
print(A)

[2 1]
[3 2 1]
[[2 4 1]
 [6 3 5]]


#### 코드 3-2 텐서플로의 행렬 생성

In [2]:
import tensorflow as tf

sess = tf.Session()

a = tf.constant([2, 1])
print(sess.run(a))

b = tf.constant([3, 2, 1])
print(sess.run(b))

A = tf.constant([[2, 4, 1], [6, 3, 5]])
print(sess.run(A))

[2 1]
[3 2 1]
[[2 4 1]
 [6 3 5]]


#### 코드 3-3 넘파이로 벡터의 합, 차, 크기 계산

In [3]:
import numpy as np
import math

a = np.array([3, 2])
b = np.array([1, 4])

print(a + b)               # 벡터의 합
print(a - b)               # 벡터의 차
print(np.linalg.norm(a))   # 벡터 a의 크기
print(np.linalg.norm(b))   # 벡터 b의 크기

# 벡터의 크기를 함수로 계산
def norm(x):
    return math.sqrt(sum([i ** 2 for i in x]))

print(norm(a))             # 벡터 a의 크기
print(norm(b))             # 벡터 b의 크기

[4 6]
[ 2 -2]
3.605551275463989
4.123105625617661
3.605551275463989
4.123105625617661


#### 코드 3-4 dot 함수로 벡터의 내적 계산

In [4]:
import numpy as np

a = np.array([3, 2])
b = np.array([1, 4])

print(a.dot(b))   # 벡터 a와 b의 내적

c = np.array([2, 1])
d = np.array([-1, 2])

print(c.dot(d))   # 벡터 c와 d의 내적

11
0


#### 코드 3-5 넘파이로 행렬의 합과 차 계산

In [5]:
import numpy as np

X = np.array([[1, 2, 3], [3, 4, 5]])
Y = np.array([[3, 4, 5], [4, 5, 6]])

print(X + Y)
print(X - Y)

[[ 4  6  8]
 [ 7  9 11]]
[[-2 -2 -2]
 [-1 -1 -1]]


#### 코드 3-6 행렬의 곱 계산

In [6]:
import numpy as np

A = np.array([[1, 2, 3], [3, 4, 5]])
B = np.array([[3, 4], [4, 5], [5, 6]])

print(A.dot(B))   # 행렬의 곱 계산

C = np.matrix([[1, 2, 3], [3, 4, 5]])
D = np.matrix([[3, 4], [4, 5], [5, 6]])

print(C * D)      # matrix 함수를 사용한 행렬의 곱 계산
print(A @ B)      # 파이썬 3.5 이후에 포함된 @ 연산자 사용

[[26 32]
 [50 62]]
[[26 32]
 [50 62]]
[[26 32]
 [50 62]]


#### 코드 3-7 넘파이로 역행렬 계산

In [7]:
import numpy as np

A = np.array([[2, 5], [1, 3]])
print(np.linalg.inv(A))

[[ 3. -5.]
 [-1.  2.]]


#### 코드 3-8 넘파이로 행렬식 계산

In [8]:
import numpy as np

A = np.array([[2, 5], [1, 3]])
print(np.linalg.det(A))

B = np.array([[1, 4, 2], [3, -1, -2], [-3, 1, 3]])
print(np.linalg.det(B))

1.0
-13.0


#### 코드 3-9 넘파이로 연립방정식 계산

In [9]:
import numpy as np

A = np.array([[2, 3], [-1, 4]])
B = np.array([7, 2])

print(np.linalg.inv(A) @ B)

[2. 1.]
