#### 코드 5-1 최소제곱법 구현

In [1]:
data = [[0, 1.5], [2, 1.7], [3, 2.1], [5, 2.2], [6, 2.8], [7, 2.9], [9, 3.2], [11, 3.7]]

def dEa(a, b):
    sum_value = 0
    for i in data:
        sum_value += i[0] * (a * i[0] + b - i[1])

    return sum_value

def dEb(a, b):
    sum_value = 0
    for i in data:
        sum_value += a * i[0] + b - i[1]

    return sum_value

eta = 0.006   # 학습률 설정
a, b = 2, 1   # 경사하강법을 시작하는 기울기값과 절편

# 오차 제곱의 합이 최소일 때의 a, b 계산
for i in range(0, 200):
    a += - eta * dEa(a, b)
    b += - eta * dEb(a, b)
    print([a, b])

[-1.3942000000000005, 1.4323036]
[1.7187556712000003, 1.0407140640303998]
[-1.1375221161598432, 1.4048404949261801]
[1.4819971626608965, 1.0756528832032122]
[-0.9216157483942804, 1.3823984078951823]
[1.2826761717376094, 1.1057128320079104]
[-0.7400162738087701, 1.3641628147141933]
[1.1148614539220698, 1.131648744496018]
[-0.5872837573059388, 1.3494488141451413]
[0.9735617753911956, 1.154096333015246]
[-0.45884054053956924, 1.337680568489723]
[0.8545769268422423, 1.1735910540769179]
[-0.350834572451975, 1.3283740031738354]
[0.7543723510105269, 1.1905839844607753]
[-0.26002440145088057, 1.3211222487809853]
[0.6699736411928423, 1.2054551814117447]
[-0.1836823959374303, 1.3155833908558379]
[0.5988777612997528, 1.2185249256794215]
[-0.11951330406005589, 1.3114701616943036]
[0.5389783371399228, 1.230063182950877]
[-0.0655857214842529, 1.3085412663121723]
[0.48850278870149977, 1.240297566044201]
[-0.02027442130582857, 1.3065940835709833]
[0.4459594266792235, 1.2494200354763365]
[0.01778817550

#### 코드 5-2 로지스틱 회귀로 손실함수가 최솟값일 확률 계산

In [2]:
import numpy as np

data = [[0, 0], [2, 0], [3, 0], [5, 0], [6, 1], [7, 1], [9, 1], [11, 1]]

def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def dEa(a, b):
    sum_value = 0
    for i in data:
        sum_value += i[0] * (sigmoid(a * i[0] + b) - i[1])

    return sum_value

def dEb(a, b):
    sum_value = 0
    for i in data:
        sum_value += sigmoid(a * i[0] + b) - i[1]

    return sum_value

eta = 0.5     # 학습률 설정
a, b = 2, 1   # 경사하강법을 시작하는 기울기값과 절편

# 최솟값으로 이동했을 때의 결정 경계 계산
for i in range(0, 200):
    a += - eta * dEa(a, b)
    b += - eta * dEb(a, b)
    print([-(b/a)])

[0.8793427752672711]
[-0.04932468721970782]
[0.13759368177537623]
[0.8015969222893439]
[-0.5381775037301996]
[0.16494546594290926]
[0.40230431270027384]
[1.1119677347331387]
[-121.81854369666472]
[0.3156464406782909]
[0.5964413671630993]
[1.3464717610574841]
[7.125090309082412]
[1.5496233162964095]
[10.96129036719981]
[0.6400208165113088]
[1.2447395964262138]
[3.7036585113474123]
[54.496284808117]
[0.5878475803137864]
[0.9694500854047747]
[1.9172483568595653]
[6.149876475981182]
[3.220949788116703]
[10.121294019556927]
[1.0204467978168437]
[1.8986833215088534]
[5.158392074870415]
[6.576846567511107]
[2.742288734541904]
[8.217738199947918]
[1.7235610769735321]
[4.120313119786962]
[10.334499986347387]
[1.1413327638262802]
[2.006215050885369]
[4.542461997115648]
[9.46410980645903]
[1.4601996620610764]
[2.7290361956655578]
[6.328541613952198]
[3.3868112385943294]
[6.599237062839191]
[3.026877015326864]
[6.32050734702618]
[3.4222442385164484]
[6.575550054883423]
[3.0768219695583037]
[6.2232

#### 코드 5-3 순전파와 역전파 계산

In [3]:
import numpy as np

# 가중치 초깃값 설정
V = np.array([[0.1, 0.3], [0.2, 0.4]])
W = np.array([[0.1, 0.3], [0.2, 0.4]])

# 지도 데이터
t = np.array([[1, 0]])

# 학습률
eta = 0.005

# 순전파
x = np.array([[1, 0.5]])
y = x.dot(V)
z = y.dot(W)

# 역전파
delta2 = z - t
grad_W = y.T.dot(delta2)
delta1 = delta2.dot(W.T)
grad_V = x.T.dot(delta1)
W -= eta * grad_W
V -= eta * grad_V
print(V)
print(W)

[[0.10005  0.30036 ]
 [0.200025 0.40018 ]]
[[0.10088 0.29974]
 [0.2022  0.39935]]


#### 코드 5-4 활성화 함수를 추가한 순전파와 역전파 계산

In [4]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def softmax(x):
    e = np.exp(x)
    return e / np.sum(e)

# 가중치 초깃값 설정
V = np.array([[0.1, 0.3], [0.2, 0.4]])
W = np.array([[0.1, 0.3], [0.2, 0.4]])

# 지도 데이터
t = np.array([[1, 0]])

# 학습률
eta = 0.005

# 순전파
x = np.array([[1, 0.5]])
y = sigmoid(x.dot(V))
z = softmax(y.dot(W))

# 역전파
delta2 = z - t
grad_W = y.T.dot(delta2)
sigmoid_dash = y * (1 - y)
delta1 = delta2.dot(W.T) * sigmoid_dash
grad_V = x.T.dot(delta1)
W -= eta * grad_W
V -= eta * grad_V
print(V)
print(W)

[[0.0998618  0.29986879]
 [0.1999309  0.39993439]]
[[0.10153499 0.29846501]
 [0.20173774 0.39826226]]
