#### 연습 문제 1 정답

In [1]:
month = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]

for i in range(12):
    print(i + 1, "월", month[i])

1 월 January
2 월 February
3 월 March
4 월 April
5 월 May
6 월 June
7 월 July
8 월 August
9 월 September
10 월 October
11 월 November
12 월 December


#### 연습 문제 2 정답

In [2]:
mark = ["Spade", "Heart", "Diamond", "Clover"]

def card(num):
    if num % 13 == 0:
        return "A"
    elif num % 13 == 10:
        return "J"
    elif num % 13 == 11:
        return "Q"
    elif num % 13 == 12:
        return "K"
    else:
        return num % 13 + 1

for i in range(52):
    print(i + 1, mark[i // 13], card(i))

1 Spade A
2 Spade 2
3 Spade 3
4 Spade 4
5 Spade 5
6 Spade 6
7 Spade 7
8 Spade 8
9 Spade 9
10 Spade 10
11 Spade J
12 Spade Q
13 Spade K
14 Heart A
15 Heart 2
16 Heart 3
17 Heart 4
18 Heart 5
19 Heart 6
20 Heart 7
21 Heart 8
22 Heart 9
23 Heart 10
24 Heart J
25 Heart Q
26 Heart K
27 Diamond A
28 Diamond 2
29 Diamond 3
30 Diamond 4
31 Diamond 5
32 Diamond 6
33 Diamond 7
34 Diamond 8
35 Diamond 9
36 Diamond 10
37 Diamond J
38 Diamond Q
39 Diamond K
40 Clover A
41 Clover 2
42 Clover 3
43 Clover 4
44 Clover 5
45 Clover 6
46 Clover 7
47 Clover 8
48 Clover 9
49 Clover 10
50 Clover J
51 Clover Q
52 Clover K


#### 연습 문제 3 정답

In [3]:
import numpy as np

score = [80, 78, 84, 69, 77, 73, 88, 64, 91, 72, 75, 62, 90, 83, 92, 60, 76, 89, 68, 70]

def standardize(x):
    return (x - np.mean(x)) / np.std(x)

print(standardize(score) * 10 + 50)

[53.04841382 50.98169259 57.18185629 41.68144703 49.94833197 45.8148895
 61.31529876 36.51464394 64.41538061 44.78152888 47.88161073 34.44792271
 63.38201999 56.14849567 65.44874123 32.38120148 48.91497135 62.34865938
 40.64808641 42.71480765]


#### 연습 문제 4 정답

In [4]:
import random

n = 1000
cnt = 0

for i in range(n):
    x = random.random()
    y = random.random()
    if x * x + y * y <= 1:
        cnt += 1

print(cnt / n)

0.783


#### 연습 문제 5 정답

In [5]:
import numpy as np

a = [[3, -2], [4, 5]]
b = [[1, -3, 4], [-2, 5, 3], [2, -1, 0]]
c = [[-1, 5, 2, -3], [0, 3, -1, 4], [2, -3, 0, -5], [-4, 2, 3, 1]]

print(np.linalg.inv(a))
print(np.linalg.inv(b))
print(np.linalg.inv(c))

[[ 0.2173913   0.08695652]
 [-0.17391304  0.13043478]]
[[-0.06382979  0.08510638  0.61702128]
 [-0.12765957  0.17021277  0.23404255]
 [ 0.17021277  0.10638298  0.0212766 ]]
[[-0.5      2.75     2.75     1.25   ]
 [ 0.1875  -0.09375 -0.21875 -0.15625]
 [-0.6875   3.34375  3.46875  1.90625]
 [-0.3125   1.15625  1.03125  0.59375]]


#### 연습 문제 6 정답

In [6]:
import numpy as np

a = [[2, 5, -4], [3, -2, 6], [-1, 3, -2]]
b = [9, 9, 4]
print(np.linalg.inv(a) @ b)

x = [[-1, 3, 5, 2], [4, -6, 3, -1], [3, 3, -4, 3], [2, -1, 2, -4]]
y = [8, -32, 26, -25]
print(np.linalg.inv(x) @ y)

[1. 3. 2.]
[-1.  3. -2.  4.]


#### 연습 문제 9-1 정답

In [7]:
import numpy as np
from sklearn import linear_model

lr = linear_model.LinearRegression()
x = np.array([[0], [2], [3], [5], [6], [7], [9], [11]])
y = np.array([1.5, 1.7, 2.1, 2.2, 2.8, 2.9, 3.2, 3.7])

# 예측 모델에 적용
lr.fit(x, y)

# 회귀계수
print(lr.coef_)

# 절편
print(lr.intercept_)

# 결정계수
print(lr.score(x, y))

[0.20519308]
1.4095872170439416
0.9714363439632973


#### 연습 문제 9-2 정답

In [8]:
import numpy as np
from sklearn import linear_model

lr = linear_model.LinearRegression()
x = [[-2.1, -3.6], [-1.4, 3.1], [0.1, -2.7], [0.8, 1.8], [1.7, -0.5], [3.2, 4.1], [5.7, -1.9], [6.2, 5.2]]
y = [-6.8, 12.2, -8.3, 3.6, -4.8, 5.8, -17.2, 3.1]

# 예측 모델에 적용
lr.fit(x, y)

# 회귀계수
print(lr.coef_)

# 절편
print(lr.intercept_)

# 결정계수
print(lr.score(x, y))

[-2.00747629  3.00565224]
-0.05311549519596337
0.9998467355398505


#### 연습 문제 9-3 정답

In [9]:
import numpy as np
from sklearn import linear_model

lr = linear_model.LinearRegression()
x = [[-3.4, 5.1, 4.1], [-2.2, 3.7, -3.4], [-1.3, -1.6, 2.6], [0.4, 7.3, -1.4], [1.4, -6.1, -3.6], [2.9, 4.2, 3.5], [4.6, 3.9, 2.9], [6.1, 2.5, -1.1]]
y = [32.5, 16.1, 2.8, 19.1, -27.1, 4.8, -3.5, -17.5]

# 예측 모델에 적용
lr.fit(x, y)

# 회귀계수
print(lr.coef_)

# 절편
print(lr.intercept_)

# 결정계수
print(lr.score(x, y))

[-3.89668886  2.98806606  0.98281857]
0.0013066645356984985
0.9999501089821065


#### 연습 문제 11 정답

In [10]:
from PIL import Image
import numpy as np

im = Image.open('image/sample.png')
ary = np.array(im)

# 이미지 크기 출력(높이×폭×색상)
print(ary.shape)

# 이미지를 흑백으로 변환해 저장
im.convert('L').save('image/sample_mono.png')

# 이미지를 회전시켜 저장(45°로 회전)
im.rotate(45).save('image/sample_rotate.png')

(3024, 4032, 3)
